[package]
name = "flare"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.0.20", features = ["full"] }
eyre = "0.6.12"
tokio = { version = "1.46.1", features = ["rt", "rt-multi-thread", "macros"] }
url = "2.5.4"
